### PR TITLE
Add Fare assembly signing

### LINKED ISSUE #25: Strong Name Signing
Would it be possible to "Strong Name Sign" the assemblies in this NuGet package?

Referencing/Using this package in a strongly-named assembly results in the following error at runtime:
Could not load file or assembly 'Fare, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

### PR DESCRIPTION
**Pull request by zvirja**
Closes #25 

Add signature to the Fare assembly.

P.S. To trigger the release, please add the tag with `v2.0.0` name, run build and publish the artifact from the `build\NuGetPackages\` folder.

### CODE REVIEW

**Comment by moodmosaic** [comment]
I will merge this and do a release as soon as I'm in front of a desktop OS :smiley:

**Comment by zvirja** [comment]
Thanks for the quick merge.

If you push a tag for v2.0.0, I could build the package and attach to comment. Just let me know if you need my help :relaxed:

**Comment by moodmosaic** [comment]
I just tagged and published Fare *2.0.0*.

FWIW, I had to [add a `Version` element in `Fare.csproj`](https://github.com/moodmosaic/Fare/commit/45869827e0853dacba29262557a0378032cdd640) so that `dotnet pack` can create a NuGet package with the right version.

**Comment by zvirja** [comment]
Thanks for pushing the package. :+1: :sports_medal:


There is no need in adding the version explicitly.  In the Fake build scripts I use Git tags to resolve the version. Therefore, after you create the `v2.0.0` tag and run the build, the produced package should have the right version. That's the same approach we have in AutoFixture.

Could you please remove the version element and see whether it works? The added property might break the automatic versioning. :unamused:

**Comment by moodmosaic** [comment]
Oh, I totally forgot about the build scripts. I will remove it.

---

A sane .csproj and the dotnet command should eliminate thoaw build scripts, eventually.

**Pull request merged**
