### PR TITLE
Remove ^ and $ markers at the beginning

### PR DESCRIPTION
**Pull request by zvirja**
The current approach when characters are removed from the result suffers from the issue that sometimes symbols are the valid parts of result. Therefore, after we remove them, the produced string no longer matches the expected regular expression.

Fixed that by removing markers _before_ regular expression generation.

### CODE REVIEW

**Comment by moodmosaic** [comment]
Interesting! :)

Do you have any test cases in mind that we could add to the test suite?

**Comment by zvirja** [comment]
Actually, this bug fails the existing tests. If you run tests for multiple times, sometimes some of them will fail. After I applied this change, tests stopped to fail (actually, they are still flucky, but due to the different reason :sweat_smile:).

Do you want me to add test cases which previously failed for each time? ;-)

**Comment by moodmosaic** [comment]
>Do you want me to add test cases which previously failed for each time? ;-)

That'd be *awesome* :+1:

**Comment by zvirja** [comment]
Added ;-)

**Pull request merged**
