### PR TITLE
Rework build script to rely on `dotnet` only

### LINKED ISSUE #42: build.cmd won't run on Windows with only .NET Core installed
```
Downloading NuGet.exe ...
Feeds used:
  C:\Users\Nikos\.nuget\packages\
  https://api.nuget.org/v3/index.json



Attempting to gather dependency information for package 'FAKE.Core.4.63.2' with respect to project 'build\tools', targeting 'Any,Version=v0.0'
Gathering dependency information took 1.65 sec
Attempting to resolve dependencies for package 'FAKE.Core.4.63.2' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'FAKE.Core.4.63.2'
Resolved actions to install package 'FAKE.Core.4.63.2'
Retrieving package 'FAKE.Core 4.63.2' from 'C:\Users\Nikos\.nuget\packages\'.
Adding package 'FAKE.Core.4.63.2' to folder 'C:\Snapshot\Fare\build\tools'
Added package 'FAKE.Core.4.63.2' to folder 'C:\Snapshot\Fare\build\tools'
Successfully installed 'FAKE.Core 4.63.2' to build\tools
Executing nuget actions took 436.42 ms
Running FAKE Build...
C:\Program Files\Git\mingw64\bin\git.exe describe --tags --long --abbrev=40 --first-parent --match=v*
v2.1.1-1-g71eaf12a6553a6ddd84a0fc52e78f19ada766d0a
Building project with version: LocalBuild
Shortened DependencyGraph for Target CompleteBuild:
<== CompleteBuild
   <== NuGetPack
      <== CleanNuGetPackages
      <== Test
         <== Build
            <== Verify
               <== RestoreNuGetPackages
               <== VerifyOnly
            <== BuildOnly
         <== TestOnly

The running order is:
  - CleanNuGetPackages
  - RestoreNuGetPackages
  - VerifyOnly
  - Verify
  - BuildOnly
  - Build
  - TestOnly
  - Test
  - NuGetPack
  - CompleteBuild
Running build with 1 worker
Starting Target: CleanNuGetPackages
Creating C:\Snapshot\Fare\build\NuGetPackages
Finished Target: CleanNuGetPackages
Starting Target: RestoreNuGetPackages
Building project: Src/Fare.sln
  c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  Src/Fare.sln /t:Restore /m  /nodeReuse:False  /v:m  /p:RestorePackages="False" /p:AssemblyVersion="2.1.0.0" /p:FileVersion="2.1.1.0" /p:InformationalVersion="2.1.1.1-71eaf12a6553a6ddd84a0fc52e78f19ada766d0a" /p:PackageVersion="2.1.1.1" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Snapshot\Fare\build\tools\FAKE.Core\tools\FakeLib.dll"
Microsoft (R) Build Engine version 4.7.3056.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Snapshot\Fare\Src\Fare.sln.metaproj : error MSB4057: The target "Restore" does not exist in the project. [C:\Snapshot\Fare\Src\Fare.sln]
Running build failed.
Error:
Building Src/Fare.sln failed with exitcode 1.

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                 Duration
------                 --------
CleanNuGetPackages     00:00:00.0025071
RestoreNuGetPackages   Failure
Total:                 00:00:01.0394329
---------------------------------------------------------------------
Status:                Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Building Src/Fare.sln failed with exitcode 1.
  2) MSB4057: C:\Snapshot\Fare\Src\Fare.sln.metaproj(0,0): The target "Restore" does not exist in the project.
---------------------------------------------------------------------
```

#30, #31, /cc @zvirja

### PR DESCRIPTION
**Pull request by zvirja**
Fixes #42 

@moodmosaic Now it should work fine without VS 😉

### CODE REVIEW

**Comment by zvirja** [comment]
I just set up the VM with Win 10 + .NET Core 1.1 SDK + .NET Core 2.1 SDK + .NET 452 SDK and tested it. Indeed, it fails with the mentioned error. It's caused by the fact we are targeting .NET 3.5 for the main library. If I change it to 452 it works fine.

I wasn't able to find .NET 3.5 SDK standalone or find the solution. Therefore, I could suggest either:
- Install VS locally and enable .NET 3.5 dev kit (installer allows to do that)
- Enable AppVeyor and use it for the build.
- Stop targeting such an old frameworks and re-target to .NET 452 😅

Sorry, I spent a few hours, but don't see any other way. Would be happy to hear if you found 😉

**Comment by moodmosaic** [comment]
Thank you for all the hard work you’ve been putting in. It’s muchbappred.

I think it’s time to target a newer version of .NET, as you correctly wrote. — The reason this is targeting such an old .NET version is because I’d never had the need to change it, until now.

Imagine that when I ported all this from Java, .NET 3.x was the latest and greatest 😆

**Comment by zvirja** [comment]
Ok then. Giving that nothing else left from the build script perspective, I this PR can be merged. If you wish to migrate project to .NET 452, please fire a separate PR and release a new major version 😉 

Let me know if you wish further actions on this PR from my side.

**Comment by moodmosaic** [comment]
>Let me know if you wish further actions on this PR from my side.

No other actions needed.

💯

**Comment by moodmosaic** [comment]
FWIW, I might consider targeting `net452` and `netstandard2.0`. Perhaps it's time to move on given the current constraints caused by the official tooling from Microsoft.

**Pull request merged**
